spring.application.name=gastos-compartidos

spring.datasource.url=jdbc:postgresql://localhost:5432/gastos_compartidos_db
spring.datasource.username=postgres
spring.datasource.password=2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081